export const ID_URL_PARAMETER_NAME = 'id';
export const ID_URL_PARAMETER = `:${ID_URL_PARAMETER_NAME}`;
export const USERNAME_URL_PARAMETER_NAME = ':username';
export const USERNAME_URL_PARAMETER = `:${USERNAME_URL_PARAMETER_NAME}`;
export const FRIEND_USERNAME_URL_PARAMETER_NAME = 'FRIENDNAME_ENDPOINT_NAME';
export const FRIEND_USERNAME_URL_PARAMETER = `:${FRIEND_USERNAME_URL_PARAMETER_NAME}`;
