version: '3.7'

services:
  app:
    container_name: vinopinions-api_devcontainer-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - ${APP_PORT}:3000
    env_file:
      - .env
    volumes:
      - ..:/workspace
    user: dev

  db:
    container_name: vinopinions-api_devcontainer-db
    image: postgres:16
    hostname: ${POSTGRES_HOSTNAME}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  minio:
    container_name: vinopinions-api_devcontainer-minio
    image: docker.io/bitnami/minio:latest
    hostname: ${S3_HOSTNAME}
    restart: unless-stopped
    ports:
      - ${S3_PORT}:9000
      - ${S3_UI_PORT}:9001
    volumes:
      - 'minio-data:/data'
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS=${S3_BUCKET}

  firebase-emulator:
    container_name: vinopinions-api_devcontainer-firebase-emulator
    hostname: ${FIREBASE_EMULATOR_HOSTNAME}
    build:
      context: ..
      dockerfile: .devcontainer/Firebase.Dockerfile
    ports:
      - ${FIREBASE_EMULATOR_UI_PORT}:4000
      - ${FIREBASE_EMULATOR_AUTH_PORT}:9099

  rabbitmq:
    container_name: vinopinions-api_devcontainer-rabbitmq
    hostname: ${RABBITMQ_HOSTNAME}
    image: rabbitmq:3.13.1-management
    ports:
      - ${RABBITMQ_UI_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/

  redis:
    container_name: vinopinions-api_devcontainer-redis
    hostname: ${REDIS_HOSTNAME}
    image: redis/redis-stack:7.2.0-v10
    ports:
      - ${REDIS_UI_PORT}:8001
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data

volumes:
  pg-data:
  minio-data:
  rabbitmq-data:
  redis-data:
