version: '3.7'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ..:/workspace
    user: dev

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  minio:
    image: docker.io/bitnami/minio:latest
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - 'minio-data:/data'
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS=${S3_BUCKET}

  firebase-emulator:
    build:
      context: ..
      dockerfile: .devcontainer/Firebase.Dockerfile
    ports:
      - 4000:4000
      - 9099:9099

volumes:
  pg-data:
  minio-data:
